---
title: "20_EDA"
output: html_notebook
---

This notebook is for visualizing the data. Specifically, I plot the distance of each of the parents from the child throughout the day. This notebook contains normal as well as animated plots that take into account this distance but not the motion of any individual.


```{r}
hist(df$distance)
hist(log(df$distance))

```


```{r}
#remove child device as main device and filter to other device = the child device. This allows for isolation of the parent distance
df1 <- df %>% filter(device != 'c0:98:e5:42:01:03') %>% filter(other_device == 'c0:98:e5:42:01:03')
```



```{r}
#plot distance of parents from child
pp <- ggplot(df1, aes(datetime, distance_m, size = .9, colour = device)) +
  geom_point(alpha = 0.7, show.legend = TRUE) +
  geom_hline(yintercept = 1, color = 'red') +
  theme_light() +
  theme(legend.title = element_blank(), panel.grid.minor = element_blank(), panel.grid.major = element_blank()) +
  xlab('Time') +
  ylab('Distance (Meters)') +
  guides(size = FALSE) 
  


plot(pp)
```


```{r}
#Both points overlayed into the same plot - animation
pq1 <- pp +
  transition_reveal(datetime)+
  theme(panel.grid.minor = element_blank(), panel.grid.major = element_blank()) +
  theme_light()



animate(pq1, duration = 25)
```



```{r}
#without legend for facet graph
pp <- ggplot(df1, aes(datetime, distance_m, size = .9, colour = device)) +
  geom_point(alpha = 0.7, show.legend = FALSE) +
  geom_hline(yintercept = 1, color = 'red') +
  theme_light() +
  theme(legend.title = element_blank(), panel.grid.minor = element_blank(), panel.grid.major = element_blank()) +
  xlab('Time') +
  ylab('Distance (Meters)') +
  guides(size = FALSE) 
  


plot(pp)
```


```{r}
#Points in separate graphs - animated
pq <- pp +
  facet_wrap(~device) +
  transition_reveal(datetime) 



animate(pq, duration = 25)
```




```{r}
# ##to save file -- 
#  b <- animate(pq1, renderer = ffmpeg_renderer())
# # 
# anim_save("animation_.mp4", b)
# # 
# a <- animate(pq1, renderer = av_renderer("animation_.mp4"), duration = 25, width = 800, height = 450)
# 
# anim_save("animation2.mp4", a)
```




