---
title: "40_child_analysis"
output: html_notebook
---
-------------------

Child with Mother
(child in motion, mother stationary)

--------------------

```{r}
merged <- merge(s_v, v_s, by = 'timestamp')
merged <- merged %>% filter(distance.x == distance.y)
```

```{r}
motion0307 <- merged %>% filter(motion.x == 1 & motion.y == 0)
```

```{r}
t <- ggplot(motion0307, aes(x=timestamp, y=distance_m.x)) +
  geom_line(alpha = .7) + 
  xlab("") +
  geom_hline(yintercept = 1, color = 'red') +
  theme_light() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.border = element_blank(), 
        axis.line = element_line(colour = "black"))
t
```
```{r}
#label touching distance yes or no
for(i in 1:nrow(merged)) {
  if (merged$motion.x[i] == 1 & merged$motion.y[i] == 0 & merged$distance_m.x[i] >= 1) {
    merged[i,'yn'] <- 1
  }
  else{
    merged[i,'yn'] <- 0 
  }
}
#count 3 seconds outside of touching distance
merged$sum <- rollapply(merged$yn,3,sum, partial = TRUE, align = "right")

#determine loop
for(i in 1:nrow(merged)) {
  if ((merged$sum[i] == 2) && (merged$sum[i-1] == 3)) {
    merged[i,'loop'] <- 1
  }
  else{
   merged[i,'loop'] <- 0 
  }
}

#ensure that loop includes at least 2 seconds of contact
for(i in 1:nrow(merged)) {
  if ((merged$loop[i] == 1) && (merged$yn[i+1] == 1)) {
    merged[i,'loop'] <- 0
  }
}

#sum number of loops
sum(merged$loop)

```


-------------------

Child with Mother
(both in motion)

--------------------

Repeat process but allow both parties to be in motion -- this will be higher than the two separate cases because there are cases where they can meet in the middle 
```{r}
for(i in 1:nrow(merged)) {
  if (merged$distance_m.x[i] >= 1) {
    merged[i,'yn'] <- 1
  }
  else{
    merged[i,'yn'] <- 0
  }
}
```

```{r}
merged$sum <- rollapply(merged$yn,3,sum, partial = TRUE, align = "right")
```

```{r}

for(i in 1:nrow(merged)) {
  if ((merged$sum[i] == 2) && (merged$sum[i-1] == 3)) {
    merged[i,'loop'] <- 1
  }
  else{
    merged[i,'loop'] <- 0 
  }
}


for(i in 1:nrow(merged)) {
  if ((merged$loop[i] == 1) && (merged$yn[i+1] == 1)) {
    merged[i,'loop'] <- 0
  }
}

```

```{r}
sum(merged$loop)
```




--------------------

Child with Father
(child in motion, father stationary)

--------------------

```{r}
merged1 <- merge(s_z, z_s, by = 'timestamp')
merged1 <- merged1 %>% filter(distance.x == distance.y)
```

```{r}
motion0306 <- merged1 %>% filter(motion.x == 1 & motion.y == 0)
```

```{r}
t <- ggplot(motion0306, aes(x=timestamp, y=distance_m.x)) +
  geom_line(alpha = .7) + 
  xlab("") +
  geom_hline(yintercept = 1, color = 'red') +
  theme_light() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.border = element_blank(), 
        axis.line = element_line(colour = "black"))
t
```
```{r}
#label touching distance yes or no
for(i in 1:nrow(merged1)) {
  if (merged1$motion.x[i] == 1 & merged1$motion.y[i] == 0 & merged1$distance_m.x[i] >= 1) {
    merged1[i,'yn'] <- 1
  }
  else{
    merged1[i,'yn'] <- 0 
  }
}
#count 3 seconds outside of touching distance
merged1$sum <- rollapply(merged1$yn,3,sum, partial = TRUE, align = "right")

#determine loop
for(i in 1:nrow(merged1)) {
  if ((merged1$sum[i] == 2) && (merged1$sum[i-1] == 3)) {
    merged1[i,'loop'] <- 1
  }
  else{
   merged1[i,'loop'] <- 0 
  }
}

#ensure that loop includes at least 2 seconds of contact
for(i in 1:nrow(merged1)) {
  if ((merged1$loop[i] == 1) && (merged1$yn[i+1] == 1)) {
    merged1[i,'loop'] <- 0
  }
}

#sum number of loops
sum(merged1$loop)

```



-------------------

Child with Father
(both in motion)

--------------------

```{r}
for(i in 1:nrow(merged1)) {
  if (merged1$distance_m.x[i] >= 1) {
    merged1[i,'yn'] <- 1
  }
  else{
    merged1[i,'yn'] <- 0
  }
}
```

```{r}
merged1$sum <- rollapply(merged1$yn,3,sum, partial = TRUE, align = "right")
```

```{r}

for(i in 1:nrow(merged1)) {
  if ((merged1$sum[i] == 2) && (merged1$sum[i-1] == 3)) {
    merged1[i,'loop'] <- 1
  }
  else{
    merged1[i,'loop'] <- 0 
  }
}


for(i in 1:nrow(merged1)) {
  if ((merged1$loop[i] == 1) && (merged1$yn[i+1] == 1)) {
    merged1[i,'loop'] <- 0
  }
}

```

```{r}
sum(merged1$loop)
```

