---
title: "41_virginia_analysis"
output: html_notebook
---

-------------------

Mother with Child
(mother in motion, child stationary)

--------------------

```{r}
merged2 <- merge(c_m, m_c, by = 'timestamp')
merged2 <- merged2 %>% filter(distance.x == distance.y)
```

```{r}
motion_0703 <- merged2 %>% filter(motion.x == 0 & motion.y == 1)
```

```{r}
t <- ggplot(motion_0703, aes(x=timestamp, y=distance_m.x)) +
  geom_line(alpha = .7) + 
  xlab("") +
  geom_hline(yintercept = 1, color = 'red') +
  theme_light() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.border = element_blank(), 
        axis.line = element_line(colour = "black"))
t
```
```{r}
#label touching distance yes or no
for(i in 1:nrow(merged2)) {
  if (merged2$motion.x[i] == 0 & merged2$motion.y[i] == 1 & merged2$distance_m.x[i] >= 1) {
    merged2[i,'yn'] <- 1
  }
  else{
    merged2[i,'yn'] <- 0 
  }
}
#count 3 seconds outside of touching distance
merged2$sum <- rollapply(merged2$yn,3,sum, partial = TRUE, align = "right")

#determine loop
for(i in 1:nrow(merged2)) {
  if ((merged2$sum[i] == 2) && (merged2$sum[i-1] == 3)) {
    merged2[i,'loop'] <- 1
  }
  else{
   merged2[i,'loop'] <- 0 
  }
}

#ensure that loop includes at least 2 seconds of contact
for(i in 1:nrow(merged2)) {
  if ((merged2$loop[i] == 1) && (merged2$yn[i+1] == 1)) {
    merged2[i,'loop'] <- 0
  }
}

#sum number of loops
sum(merged2$loop)

```





Plot proportion of time spent in touching distance vs outside of touching distance

```{r}
merged2$touching <- ifelse(merged2$distance_m.y <= 1, 1, 0)
```


```{r}
ggplot(merged2, aes(touching, y = ..prop..)) +
  geom_bar(width = .5, fill = "darkolivegreen") +
  xlab("Touching") +
  ylab("Percent of time") +
  theme_light() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), text = element_text(size=20)) +
  scale_y_continuous(labels = scales::percent_format())
```

```{r}
#Look at proportions - in touching distance 68% of the time
prop.table(table(merged2$touching)) %>% round(2)
```



