---
title: "42_zeke_analysis"
output: html_notebook
---

-------------------

Father with Child
(father in motion, child stationary)

--------------------

```{r}
merged3 <- merge(s_z, z_s, by = 'timestamp') 
merged3 <- merged3 %>% filter(distance.x == distance.y)
```

```{r}
motion_0603 <- merged3 %>% filter(motion.x == 0 & motion.y == 1)
```

```{r}
t <- ggplot(motion_0603, aes(x=timestamp, y=distance_m.x)) +
  geom_line(alpha = .7) + 
  xlab("") +
  geom_hline(yintercept = 1, color = 'red') +
  theme_light() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.border = element_blank(), 
        axis.line = element_line(colour = "black"))
t
```
```{r}
#label touching distance yes or no
for(i in 1:nrow(merged3)) {
  if (merged3$motion.x[i] == 0 & merged3$motion.y[i] == 1 & merged3$distance_m.x[i] >= 1) {
    merged3[i,'yn'] <- 1
  }
  else{
    merged3[i,'yn'] <- 0 
  }
}
#count 3 seconds outside of touching distance
merged3$sum <- rollapply(merged3$yn,3,sum, partial = TRUE, align = "right")

#determine loop
for(i in 1:nrow(merged3)) {
  if ((merged3$sum[i] == 2) && (merged3$sum[i-1] == 3)) {
    merged3[i,'loop'] <- 1
  }
  else{
   merged3[i,'loop'] <- 0 
  }
}

#ensure that loop includes at least 2 seconds of contact
for(i in 1:nrow(merged3)) {
  if ((merged3$loop[i] == 1) && (merged3$yn[i+1] == 1)) {
    merged3[i,'loop'] <- 0
  }
}

#sum number of loops
sum(merged3$loop)

```





```{r}
merged3$touching <- ifelse(merged3$distance_m.y <= 1, 1, 0)
```


```{r}
ggplot(merged3, aes(touching, y = ..prop..)) +
  geom_bar(width = .5) +
  theme_light() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  scale_y_continuous(labels = scales::percent_format())
```

```{r}
prop.table(table(merged3$touching)) %>% round(2)
```

