---
title: "R Notebook"
output: html_notebook
---

----------------------------------

All family members loops with child

-----------------------------------


```{r}
m <- inner_join(s_z, z_s, by = 'timestamp')
m <- m %>% filter(distance.x == distance.y)
m <- m %>% select(timestamp, device.x, device.y, motion.x, motion.y, other_device.x, other_device.y, distance_m.x, time.x)
m <-m %>% rename(time = time.x, distance = distance_m.x )
m <- reshape(m, idvar = "timestamp", timevar = "device.y", direction = "wide")
```



```{r}
n <- inner_join(s_v, v_s, by = 'timestamp')
n <- n %>% filter(distance.x == distance.y)
n <- n %>% select(timestamp, device.x, device.y, motion.x, motion.y, other_device.x, other_device.y, distance_m.x, time.x)
n <- n %>% rename(time = time.x, distance = distance_m.x )
n <- reshape(n, idvar = "timestamp", timevar = "device.y", direction = "wide")
```

```{r}
mn <-inner_join(m,n, by = 'timestamp') %>% 
  select(-c('timestamp', starts_with('other_device'), 'time.c0:98:e5:42:01:07', 'device.x.c0:98:e5:42:01:07', 'motion.x.c0:98:e5:42:01:07'))
mn <- mn %>% rename(time = 'time.c0:98:e5:42:01:06', motion_03 = 'motion.x.c0:98:e5:42:01:06', motion_06 = 'motion.y.c0:98:e5:42:01:06', motion_07 = 'motion.y.c0:98:e5:42:01:07', device = 'device.x.c0:98:e5:42:01:06', distance_06 = 'distance.c0:98:e5:42:01:06', distance_07 = 'distance.c0:98:e5:42:01:07')

```

```{r}
for(i in 1:nrow(mn)) {
  if ((mn$distance_06[i] >= 1) & (mn$distance_07[i] >= 1)) {
    mn[i,'yn'] <- 1
  }
  else{
    mn[i,'yn'] <- 0
  }
}

```


```{r}
mn$sum <- rollapply(mn$yn,3,sum, partial = TRUE, align = "right")
```


```{r}

for(i in 1:nrow(mn)) {
  if ((mn$sum[i] == 2) && (mn$sum[i-1] == 3)) {
    mn[i,'loop'] <- 1
  }
  else{
    mn[i,'loop'] <- 0 
  }
}


for(i in 1:nrow(mn)) {
  if ((mn$loop[i] == 1) && (mn$yn[i+1] == 1)) {
    mn[i,'loop'] <- 0
  }
}
```

```{r}
sum(mn$loop)
```


**thinking through loop initiation and closing (arrivals and departures) 
Note: this is using loops as an indicator of arrival


```{r}
# mn %>% filter(loop == 1) %>% mutate(
#     touching = case_when(
#       (distance_06 < 1 & distance_07 < 1) ~ "both",
#       distance_07 < 1 ~ "07",
#       distance_06 < 1 ~ "06"
#     ))
```

```{r}
mn <- mn %>% mutate(
  touching = case_when(
  grepl(1, loop) & (distance_06 < 1 & distance_07 < 1) ~ "both",
  grepl(1, loop) & distance_07 < 1 ~ "07",
  grepl(1, loop) & distance_06 < 1 ~ "06",
  grepl(0, loop) ~ ""))

mn %>% count(touching)
```

```{r}
mn <- mn %>% mutate(
  arrival = case_when(
  grepl("07", touching) & motion_03 == 1 & motion_07 == 0 ~ "child",
  grepl("07", touching) & motion_03 == 0 & motion_07 == 1 ~ "mother",
  grepl("07", touching) & motion_03 == 1 & motion_07 == 1 ~ "multiple",
  grepl("06", touching) & motion_03 == 1 & motion_06 == 0 ~ "child",
  grepl("06", touching) & motion_03 == 0 & motion_06 == 1 ~ "father",
  grepl("06", touching) & motion_03 == 1 & motion_06 == 1 ~ "multiple",
  grepl("both", touching) & motion_03 == 1 & motion_06 == 0 & motion_07 == 0 ~ "child",
  grepl("both", touching) & motion_03 == 0 & motion_06 == 1 & motion_07 == 0 ~ "father",
  grepl("both", touching) & motion_03 == 0 & motion_06 == 0 & motion_07 == 1 ~ "mother",
  grepl("both", touching) & motion_03 == 1 & motion_06 == 1 & motion_07 == 0 ~ "multiple",
  grepl("both", touching) & motion_03 == 0 & motion_06 == 1 & motion_07 == 1 ~ "multiple",
  grepl("both", touching) & motion_03 == 1 & motion_06 == 0 & motion_07 == 1 ~ "multiple",
  grepl("both", touching) & motion_03 == 1 & motion_06 == 1 & motion_07 == 1 ~ "multiple",
  grepl(1, loop) ~ "none",
  grepl(0, loop) ~ ""))

mn %>% count(arrival)
```


```{r}
for(i in 1:nrow(mn)){
  if(mn$arrival[i] == "none"){
      mn$arrival[i] = case_when(
        grepl("07", mn$touching[i]) & mn$motion_03[i-1] == 1 & mn$motion_07[i-1] == 0 ~ "child",
        grepl("07", mn$touching[i]) & mn$motion_03[i-1] == 0 & mn$motion_07[i-1] == 1 ~ "mother",
        grepl("07", mn$touching[i]) & mn$motion_03[i-1] == 1 & mn$motion_07[i-1] == 1 ~ "multiple",
        grepl("06", mn$touching[i]) & mn$motion_03[i-1] == 1 & mn$motion_06[i-1] == 0 ~ "child",
        grepl("06", mn$touching[i]) & mn$motion_03[i-1] == 0 & mn$motion_06[i-1] == 1 ~ "father",
        grepl("06", mn$touching[i]) & mn$motion_03[i-1] == 1 & mn$motion_06[i-1] == 1 ~ "multiple",
        grepl("both", mn$touching[i]) & mn$motion_03[i-1] == 1 & mn$motion_06[i-1] == 0 & mn$motion_07[i-1] == 0 ~ "child",
        grepl("both", mn$touching[i]) & mn$motion_03[i-1] == 0 & mn$motion_06[i-1] == 1 & mn$motion_07[i-1] == 0 ~ "father",
        grepl("both", mn$touching[i]) & mn$motion_03[i-1] == 0 & mn$motion_06[i-1] == 0 & mn$motion_07[i-1] == 1 ~ "mother",
        grepl("both", mn$touching[i]) & mn$motion_03[i-1] == 1 & mn$motion_06[i-1] == 1 & mn$motion_07[i-1] == 0 ~ "multiple",
        grepl("both", mn$touching[i]) & mn$motion_03[i-1] == 0 & mn$motion_06[i-1] == 1 & mn$motion_07[i-1] == 1 ~ "multiple",
        grepl("both", mn$touching[i]) & mn$motion_03[i-1] == 1 & mn$motion_06[i-1] == 0 & mn$motion_07[i-1] == 1 ~ "multiple",
        grepl("both", mn$touching[i]) & mn$motion_03[i-1] == 1 & mn$motion_06[i-1] == 1 & mn$motion_07[i-1] == 1 ~ "multiple"
    )
  }
}
mn %>% count(arrival)
```


```{r}
for(i in 1:nrow(mn)){
  if(is.na(mn$arrival[i])){
      mn$arrival[i] = case_when(
        grepl("07", mn$touching[i]) & mn$motion_03[i-2] == 1 & mn$motion_07[i-2] == 0 ~ "child",
        grepl("07", mn$touching[i]) & mn$motion_03[i-2] == 0 & mn$motion_07[i-2] == 1 ~ "mother",
        grepl("07", mn$touching[i]) & mn$motion_03[i-2] == 1 & mn$motion_07[i-2] == 1 ~ "multiple",
        grepl("06", mn$touching[i]) & mn$motion_03[i-2] == 1 & mn$motion_06[i-2] == 0 ~ "child",
        grepl("06", mn$touching[i]) & mn$motion_03[i-2] == 0 & mn$motion_06[i-2] == 1 ~ "father",
        grepl("06", mn$touching[i]) & mn$motion_03[i-2] == 1 & mn$motion_06[i-2] == 1 ~ "multiple",
        grepl("both", mn$touching[i]) & mn$motion_03[i-2] == 1 & mn$motion_06[i-2] == 0 & mn$motion_07[i-2] == 0 ~ "child",
        grepl("both", mn$touching[i]) & mn$motion_03[i-2] == 0 & mn$motion_06[i-2] == 1 & mn$motion_07[i-2] == 0 ~ "father",
        grepl("both", mn$touching[i]) & mn$motion_03[i-2] == 0 & mn$motion_06[i-2] == 0 & mn$motion_07[i-2] == 1 ~ "mother",
        grepl("both", mn$touching[i]) & mn$motion_03[i-2] == 1 & mn$motion_06[i-2] == 1 & mn$motion_07[i-2] == 0 ~ "multiple",
        grepl("both", mn$touching[i]) & mn$motion_03[i-2] == 0 & mn$motion_06[i-2] == 1 & mn$motion_07[i-2] == 1 ~ "multiple",
        grepl("both", mn$touching[i]) & mn$motion_03[i-2] == 1 & mn$motion_06[i-2] == 0 & mn$motion_07[i-2] == 1 ~ "multiple",
        grepl("both", mn$touching[i]) & mn$motion_03[i-2] == 1 & mn$motion_06[i-2] == 1 & mn$motion_07[i-2] == 1 ~ "multiple"
    )
  }
}
mn %>% count(arrival)
```

