---
title: "44_check-ins"
output: html_notebook
---

A "check-in" is when one or more parents are in touching distance - this will have the opposite label of the "yn" variable

```{r}
mn$checkin <- ifelse((mn$distance_06 < 1 | mn$distance_07 <1),1,0)
mn <- mn %>% filter(!is.na(checkin))
```

```{r}
for(i in 1:nrow(mn)) {
  if (((mn$distance_06[i] >= 1) | (is.na(mn$distance_06[i]))) & ((mn$distance_07[i] >= 1) | (is.na(mn$distance_07[i])))) {
    mn[i,'yn'] <- 1
  }
  else{
    mn[i,'yn'] <- 0
  }
}

```


```{r}
mn$sum <- rollapply(mn$yn,3,sum, partial = TRUE, align = "right")
```


```{r}

for(i in 1:nrow(mn)) {
  if ((mn$sum[i] == 2) && (mn$sum[i-1] == 3)) {
    mn[i,'loop'] <- 1
  }
  else{
    mn[i,'loop'] <- 0 
  }
}


for(i in 1:nrow(mn)) {
  if ((mn$loop[i] == 1) && (mn$yn[i+1] == 1)) {
    mn[i,'loop'] <- 0
  }
}
```

```{r}
sum(mn$loop)
```

```{r}
table(mn$checkin)
```

```{r}
ggplot(mn, aes(checkin, y = ..prop..)) +
  geom_bar(width = .5) +
  theme_light() +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  scale_y_continuous(labels = scales::percent_format())
```

```{r}
prop.table(table(mn$checkin)) %>% round(2)
```

When either parent was within touching distance of the child, how often was each person in motion?

```{r}
mn %>% filter(checkin ==1) %>% filter(motion_03 ==1) %>% summarise(n()/nrow(mn %>% filter(checkin ==1)))
mn %>% filter(checkin ==1) %>% filter(motion_06 ==1) %>% summarise(n()/nrow(mn %>% filter(checkin ==1)))
mn %>% filter(checkin ==1) %>% filter(motion_07 ==1) %>% summarise(n()/nrow(mn %>% filter(checkin ==1)))
```

Child = 11%
Father = 22%
Mother = 18%



__________________________________________

Arrivals

__________________________________________

```{r}
mn <- mn %>% mutate(
  touching = case_when(
  grepl(1, loop) & (distance_06 < 1 & distance_07 < 1) ~ "both",
  grepl(1, loop) & distance_07 < 1 ~ "07",
  grepl(1, loop) & distance_06 < 1 ~ "06",
  grepl(0, loop) ~ ""))

mn %>% count(touching)
```

```{r}
mn <- mn %>% mutate(
  arrival = case_when(
  grepl("07", touching) & motion_03 == 1 & motion_07 == 0 ~ "child",
  grepl("07", touching) & motion_03 == 0 & motion_07 == 1 ~ "mother",
  grepl("07", touching) & motion_03 == 1 & motion_07 == 1 ~ "multiple_child",
  grepl("06", touching) & motion_03 == 1 & motion_06 == 0 ~ "child",
  grepl("06", touching) & motion_03 == 0 & motion_06 == 1 ~ "father",
  grepl("06", touching) & motion_03 == 1 & motion_06 == 1 ~ "multiple_child",
  grepl("both", touching) & motion_03 == 1 & motion_06 == 0 & motion_07 == 0 ~ "child",
  grepl("both", touching) & motion_03 == 0 & motion_06 == 1 & motion_07 == 0 ~ "father",
  grepl("both", touching) & motion_03 == 0 & motion_06 == 0 & motion_07 == 1 ~ "mother",
  grepl("both", touching) & motion_03 == 1 & motion_06 == 1 & motion_07 == 0 ~ "multiple_child",
  grepl("both", touching) & motion_03 == 0 & motion_06 == 1 & motion_07 == 1 ~ "multiple_parents",
  grepl("both", touching) & motion_03 == 1 & motion_06 == 0 & motion_07 == 1 ~ "multiple_child",
  grepl("both", touching) & motion_03 == 1 & motion_06 == 1 & motion_07 == 1 ~ "multiple_child",
  grepl(1, loop) ~ "none",
  grepl(0, loop) ~ ""))

mn %>% count(arrival)
```


```{r}
for(i in 1:nrow(mn)){
  if(mn$arrival[i] == "none"){
      mn$arrival[i] = case_when(
        grepl("07", mn$touching[i]) & mn$motion_03[i-1] == 1 & mn$motion_07[i-1] == 0 ~ "child",
        grepl("07", mn$touching[i]) & mn$motion_03[i-1] == 0 & mn$motion_07[i-1] == 1 ~ "mother",
        grepl("07", mn$touching[i]) & mn$motion_03[i-1] == 1 & mn$motion_07[i-1] == 1 ~ "multiple_child",
        grepl("06", mn$touching[i]) & mn$motion_03[i-1] == 1 & mn$motion_06[i-1] == 0 ~ "child",
        grepl("06", mn$touching[i]) & mn$motion_03[i-1] == 0 & mn$motion_06[i-1] == 1 ~ "father",
        grepl("06", mn$touching[i]) & mn$motion_03[i-1] == 1 & mn$motion_06[i-1] == 1 ~ "multiple_child",
        grepl("both", mn$touching[i]) & mn$motion_03[i-1] == 1 & mn$motion_06[i-1] == 0 & mn$motion_07[i-1] == 0 ~ "child",
        grepl("both", mn$touching[i]) & mn$motion_03[i-1] == 0 & mn$motion_06[i-1] == 1 & mn$motion_07[i-1] == 0 ~ "father",
        grepl("both", mn$touching[i]) & mn$motion_03[i-1] == 0 & mn$motion_06[i-1] == 0 & mn$motion_07[i-1] == 1 ~ "mother",
        grepl("both", mn$touching[i]) & mn$motion_03[i-1] == 1 & mn$motion_06[i-1] == 1 & mn$motion_07[i-1] == 0 ~ "multiple_child",
        grepl("both", mn$touching[i]) & mn$motion_03[i-1] == 0 & mn$motion_06[i-1] == 1 & mn$motion_07[i-1] == 1 ~ "multiple_parents",
        grepl("both", mn$touching[i]) & mn$motion_03[i-1] == 1 & mn$motion_06[i-1] == 0 & mn$motion_07[i-1] == 1 ~ "multiple_child",
        grepl("both", mn$touching[i]) & mn$motion_03[i-1] == 1 & mn$motion_06[i-1] == 1 & mn$motion_07[i-1] == 1 ~ "multiple_child"
    )
  }
}
mn %>% count(arrival)
```


```{r}
for(i in 1:nrow(mn)){
  if(is.na(mn$arrival[i])){
      mn$arrival[i] = case_when(
        grepl("07", mn$touching[i]) & mn$motion_03[i-2] == 1 & mn$motion_07[i-2] == 0 ~ "child",
        grepl("07", mn$touching[i]) & mn$motion_03[i-2] == 0 & mn$motion_07[i-2] == 1 ~ "mother",
        grepl("07", mn$touching[i]) & mn$motion_03[i-2] == 1 & mn$motion_07[i-2] == 1 ~ "multiple_child",
        grepl("06", mn$touching[i]) & mn$motion_03[i-2] == 1 & mn$motion_06[i-2] == 0 ~ "child",
        grepl("06", mn$touching[i]) & mn$motion_03[i-2] == 0 & mn$motion_06[i-2] == 1 ~ "father",
        grepl("06", mn$touching[i]) & mn$motion_03[i-2] == 1 & mn$motion_06[i-2] == 1 ~ "multiple_child",
        grepl("both", mn$touching[i]) & mn$motion_03[i-2] == 1 & mn$motion_06[i-2] == 0 & mn$motion_07[i-2] == 0 ~ "child",
        grepl("both", mn$touching[i]) & mn$motion_03[i-2] == 0 & mn$motion_06[i-2] == 1 & mn$motion_07[i-2] == 0 ~ "father",
        grepl("both", mn$touching[i]) & mn$motion_03[i-2] == 0 & mn$motion_06[i-2] == 0 & mn$motion_07[i-2] == 1 ~ "mother",
        grepl("both", mn$touching[i]) & mn$motion_03[i-2] == 1 & mn$motion_06[i-2] == 1 & mn$motion_07[i-2] == 0 ~ "multiple_child",
        grepl("both", mn$touching[i]) & mn$motion_03[i-2] == 0 & mn$motion_06[i-2] == 1 & mn$motion_07[i-2] == 1 ~ "multiple_parents",
        grepl("both", mn$touching[i]) & mn$motion_03[i-2] == 1 & mn$motion_06[i-2] == 0 & mn$motion_07[i-2] == 1 ~ "multiple_child",
        grepl("both", mn$touching[i]) & mn$motion_03[i-2] == 1 & mn$motion_06[i-2] == 1 & mn$motion_07[i-2] == 1 ~ "multiple_child"
    )
  }
}
mn %>% count(arrival)
```

```{r}
mn$arrival[1] <- "start"
```


```{r}
rows <- nrow(mn_new) -1
for(i in 1:rows) {
  if(is.na(mn$arrival[i])){
    mn$arrival[i] <- "none"
  }
}
```



__________________________________________

Departures

__________________________________________

Look at who is in touching distance at every second during a check-in 
```{r}

mn_new <- mn %>% mutate(
  touching = case_when(
  grepl(1, checkin) & (distance_06 < 1 & distance_07 < 1) ~ "both",
  grepl(1, checkin) & (distance_07 < 1 & (distance_06 >= 1 | is.na(distance_06))) ~ "07",
  grepl(1, checkin) & (distance_06 < 1 & (distance_07 >= 1 | is.na(distance_07))) ~ "06",
  grepl(0, checkin) ~ ""))

mn_new %>% count(touching)

```

```{r}
# mn_new <- mn_new %>% mutate(
#   departure = case_when(
#   grepl("07", touching) & motion_03 == 1 & motion_07 == 0 ~ "child",
#   grepl("07", touching) & motion_03 == 0 & motion_07 == 1 ~ "mother",
#   grepl("07", touching) & motion_03 == 1 & motion_07 == 1 ~ "multiple_child",
#   grepl("07", touching) & motion_03 == 0 & motion_07 == 0 ~ "none",
#   grepl("06", touching) & motion_03 == 1 & motion_06 == 0 ~ "child",
#   grepl("06", touching) & motion_03 == 0 & motion_06 == 1 ~ "father",
#   grepl("06", touching) & motion_03 == 1 & motion_06 == 1 ~ "multiple_child",
#   grepl("06", touching) & motion_03 == 0 & motion_06 == 0 ~ "none",
#   grepl("both", touching) & motion_03 == 1 & motion_06 == 0 & motion_07 == 0 ~ "child",
#   grepl("both", touching) & motion_03 == 0 & motion_06 == 1 & motion_07 == 0 ~ "father",
#   grepl("both", touching) & motion_03 == 0 & motion_06 == 0 & motion_07 == 1 ~ "mother",
#   grepl("both", touching) & motion_03 == 1 & motion_06 == 1 & motion_07 == 0 ~ "multiple_child",
#   grepl("both", touching) & motion_03 == 0 & motion_06 == 1 & motion_07 == 1 ~ "multiple_parents",
#   grepl("both", touching) & motion_03 == 1 & motion_06 == 0 & motion_07 == 1 ~ "multiple_child",
#   grepl("both", touching) & motion_03 == 1 & motion_06 == 1 & motion_07 == 1 ~ "multiple_child",
#   grepl("both", touching) & motion_03 == 0 & motion_06 == 0 & motion_07 == 0 ~ "none",
#   grepl(0, loop) ~ ""))

#mn_new %>% count(departure)
```


```{r}
mn_new <- mn_new %>% mutate(
  movement = case_when(
  grepl("07", touching) & motion_03 == 1 & motion_07 == 0 ~ "child",
  grepl("07", touching) & motion_03 == 0 & motion_07 == 1 ~ "mother",
  grepl("07", touching) & motion_03 == 1 & motion_07 == 1 ~ "multiple_child",
  grepl("07", touching) & motion_03 == 0 & motion_07 == 0 ~ "none",
  grepl("06", touching) & motion_03 == 1 & motion_06 == 0 ~ "child",
  grepl("06", touching) & motion_03 == 0 & motion_06 == 1 ~ "father",
  grepl("06", touching) & motion_03 == 1 & motion_06 == 1 ~ "multiple_child",
  grepl("06", touching) & motion_03 == 0 & motion_06 == 0 ~ "none",
  grepl("both", touching) & motion_03 == 1 & motion_06 == 0 & motion_07 == 0 ~ "child",
  grepl("both", touching) & motion_03 == 0 & motion_06 == 1 & motion_07 == 0 ~ "father",
  grepl("both", touching) & motion_03 == 0 & motion_06 == 0 & motion_07 == 1 ~ "mother",
  grepl("both", touching) & motion_03 == 1 & motion_06 == 1 & motion_07 == 0 ~ "multiple_child",
  grepl("both", touching) & motion_03 == 0 & motion_06 == 1 & motion_07 == 1 ~ "multiple_parents",
  grepl("both", touching) & motion_03 == 1 & motion_06 == 0 & motion_07 == 1 ~ "multiple_child",
  grepl("both", touching) & motion_03 == 1 & motion_06 == 1 & motion_07 == 1 ~ "multiple_child",
  grepl("both", touching) & motion_03 == 0 & motion_06 == 0 & motion_07 == 0 ~ "none",
  grepl(0, checkin) & motion_03 == 1 & motion_07 == 0 ~ "child",
  grepl(0, checkin) & motion_03 == 0 & motion_07 == 1 ~ "mother",
  grepl(0, checkin) & motion_03 == 1 & motion_07 == 1 ~ "multiple_child",
  grepl(0, checkin) & motion_03 == 0 & motion_07 == 0 ~ "none",
  grepl(0, checkin) & motion_03 == 1 & motion_06 == 0 ~ "child",
  grepl(0, checkin) & motion_03 == 0 & motion_06 == 1 ~ "father",
  grepl(0, checkin) & motion_03 == 1 & motion_06 == 1 ~ "multiple_child",
  grepl(0, checkin) & motion_03 == 0 & motion_06 == 0 ~ "none",
  grepl(0, checkin) & motion_03 == 1 & motion_06 == 0 & motion_07 == 0 ~ "child",
  grepl(0, checkin) & motion_03 == 0 & motion_06 == 1 & motion_07 == 0 ~ "father",
  grepl(0, checkin) & motion_03 == 0 & motion_06 == 0 & motion_07 == 1 ~ "mother",
  grepl(0, checkin) & motion_03 == 1 & motion_06 == 1 & motion_07 == 0 ~ "multiple_child",
  grepl(0, checkin) & motion_03 == 0 & motion_06 == 1 & motion_07 == 1 ~ "multiple_parents",
  grepl(0, checkin) & motion_03 == 1 & motion_06 == 0 & motion_07 == 1 ~ "multiple_child",
  grepl(0, checkin) & motion_03 == 1 & motion_06 == 1 & motion_07 == 1 ~ "multiple_child",
  grepl(0, checkin) & motion_03 == 0 & motion_06 == 0 & motion_07 == 0 ~ "none" 
  )
)
```




```{r}

rows <- nrow(mn_new) -1
for(i in 1:rows) {
  if((mn_new$sum[i] < 3)){
    mn_new[i,'in_loop'] <- 1
  } else{
    mn_new[i,'in_loop'] <- ""
  }
}




```


```{r}
rows <- nrow(mn_new) -1
for(i in 1:rows) {
  if((mn_new$sum[i] == 3) && (mn_new$sum[i-1] < 3) && (mn_new$in_loop[i-4] == 1)){
    mn_new[i-3,'departure'] <- mn_new$movement[i-3]
  } else{
    mn_new[i-3,'departure'] <- ""
  }
}
```




```{r}
table(mn_new$departure)
table(mn_new$arrival)
```

